-- MySQL Script generated by MySQL Workbench
-- dom 07 abr 2019 15:16:48 CEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PracticaBDD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PracticaBDD` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `PracticaBDD` ;

-- -----------------------------------------------------
-- Table `PracticaBDD`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PracticaBDD`.`Usuarios` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fech_nacimiento` DATE NULL,
  `aficiones` MEDIUMTEXT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PracticaBDD`.`Mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PracticaBDD`.`Mensajes` (
  `idMensaje` INT NOT NULL,
  `contenido` MEDIUMTEXT NULL,
  `posteado` INT NOT NULL,
  `fecha_envio` DATETIME NULL,
  PRIMARY KEY (`idMensaje`),
  INDEX `fk_Mensajes_1_idx` (`posteado` ASC),
  CONSTRAINT `fk_Mensajes_1`
    FOREIGN KEY (`posteado`)
    REFERENCES `PracticaBDD`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PracticaBDD`.`Privados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PracticaBDD`.`Privados` (
  `idPrivados` INT NOT NULL,
  `content` MEDIUMTEXT NULL,
  `remitido` INT NULL,
  `fecha_envio` DATETIME NULL,
  PRIMARY KEY (`idPrivados`),
  INDEX `fk_Privados_1_idx` (`remitido` ASC),
  CONSTRAINT `fk_Privados_1`
    FOREIGN KEY (`remitido`)
    REFERENCES `PracticaBDD`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PracticaBDD`.`RelacionAmigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PracticaBDD`.`RelacionAmigos` (
  `idAmigos` INT NULL,
  `usuario_amigo` INT NULL,
  INDEX `fk_RelacionAmigos_1_idx` (`idAmigos` ASC),
  INDEX `fk_RelacionAmigos_2_idx` (`usuario_amigo` ASC),
  CONSTRAINT `fk_RelacionAmigos_1`
    FOREIGN KEY (`idAmigos`)
    REFERENCES `PracticaBDD`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RelacionAmigos_2`
    FOREIGN KEY (`usuario_amigo`)
    REFERENCES `PracticaBDD`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
