-- MySQL Script generated by MySQL Workbench
-- sáb 13 abr 2019 10:23:33 CEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema social_bbdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `social_bbdd` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `social_bbdd` ;

-- -----------------------------------------------------
-- Table `social_bbdd`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_bbdd`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `edad` INT NULL,
  `aficiones` MEDIUMTEXT NULL,
  `fecha_creacion` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_bbdd`.`Mensajes_enviados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_bbdd`.`Mensajes_enviados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `remitente` INT NULL,
  `mensaje_remitido` INT NULL,
  `fecha_envio` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Mensajes_enviados_1_idx` (`remitente` ASC),
  CONSTRAINT `fk_Mensajes_enviados_1`
    FOREIGN KEY (`remitente`)
    REFERENCES `social_bbdd`.`Usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_bbdd`.`Mensajes_recibidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_bbdd`.`Mensajes_recibidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` LONGTEXT NULL,
  `remitente` INT NULL,
  `destinatario` INT NULL,
  `fecha_envio` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Mensajes_recibidos_1_idx` (`destinatario` ASC),
  INDEX `fk_Mensajes_recibidos_2_idx` (`remitente` ASC),
  CONSTRAINT `fk_Mensajes_recibidos_1`
    FOREIGN KEY (`destinatario`)
    REFERENCES `social_bbdd`.`Usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mensajes_recibidos_2`
    FOREIGN KEY (`remitente`)
    REFERENCES `social_bbdd`.`Mensajes_enviados` (`remitente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_bbdd`.`Privados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_bbdd`.`Privados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` LONGTEXT NULL,
  `destinatario` INT NULL,
  `fecha_envio` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Privados_1_idx` (`destinatario` ASC),
  CONSTRAINT `fk_Privados_1`
    FOREIGN KEY (`destinatario`)
    REFERENCES `social_bbdd`.`Usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `social_bbdd`.`Amistad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `social_bbdd`.`Amistad` (
  `idAmigo` INT NULL,
  `idAmistad` INT NULL,
  INDEX `fk_Amistad_1_idx` (`idAmigo` ASC),
  INDEX `fk_Amistad_2_idx` (`idAmistad` ASC),
  CONSTRAINT `fk_Amistad_1`
    FOREIGN KEY (`idAmigo`)
    REFERENCES `social_bbdd`.`Usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Amistad_2`
    FOREIGN KEY (`idAmistad`)
    REFERENCES `social_bbdd`.`Usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
